USE final_project;

CREATE TABLE item_table (
    item_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    item_name VARCHAR(100),
    item_price DOUBLE(7,2),
    restaurant_id INT,
    inventory INT
    );

INSERT INTO final_project.item_table
    ( item_name, item_price, restaurant_id )
VALUES
    ('Meat, Olive & Cheese Plate', 15, 1),
    ('Fruit, Nut & Cheese Plate', 12, 1),
    ('Mussels Al Forno', 10, 1),
    ('Meatballs Al Forno', 9, 1),
    ('Braised Calamari', 9, 1),
    ('Frisee', 7, 1),
    ('Arugula', 5, 1),
    ('Roasted Beet', 5, 1),
    ('Margherita', 12, 1),
    ('Patate Arrosto', 14, 1),
    ('Salumi', 13, 1),
    ('Parma', 15, 1),
    ('Salsiccia', 15, 1),
    ('Fiorellini', 13, 1),
    ('Pesto', 16, 1),
    ('Mela', 13, 1),
    ('Funghi', 14, 1),
    ('Dolce Verde', 14, 1),
    ('Colazione', 13, 1),
    ('Vongole', 16, 1),
    ('Pollo Al Mattone', 18, 1),
    ('Bistecca Tagliata', 19, 1),
    ('Alehouse Chicken Wings', 11.5, 2),
    ('Mozzarella Sticks', 9.25, 2),
    ('Onion Rings', 9, 2),
    ('Jalapeño Artichoke Dip', 9.75, 2),
    ('Alehouse Chips & Fresh Kitchen Salsa', 5.5, 2),
    ('Steak Fajita Quesadilla', 11.5, 2),
    ("Brewer's Nachos", 14, 2),
    ('Chicken Quesadilla', 10.5, 2),
    ('Jumbo Finger Steaks', 9.75, 2),
    ('Chicken Club Wrap', 11, 2),
    ('Chicken Caesar Wrap', 11, 2),
    ('Thai Chicken Wrap', 11, 2),
    ('Vandal Brat', 10.25, 2),
    ('Alehouse Sandwich', 10.25, 2),
    ('Southwestern Meatloaf Sandwich', 11.5, 2),
    ('Steak Sandwich', 13, 2),
    ('Chicken Fingers', 11, 2),
    ('Buffalo Chicken Sandwich', 10.5, 2),
    ('Reuben', 9.5, 2),
    ('French Dip', 10.5, 2),
    ('Portobello Mushroom', 11.75, 2),
    ('Meatball Sub', 11.5, 2),
    ('Philly Cheese Steak', 11, 2),
    ('Chicken Cordon Bleu', 10.5, 2),
    ('The Vandal', 14.75, 2),
    ('Vandal Huckleberry Bacon', 12.75, 2),
    ('California', 13.75, 2),
    ('Bleu Cheese', 12, 2),
    ('Ranch', 12.75, 2),
    ('Hula', 12, 2),
    ('Boise State Basic', 10.25, 2),
    ('Mushroom Swiss Classic', 12, 2),
    ('Groobz', 12.75, 2),
    ('Jumbo Pork Fritter', 11.5, 2),
    ('Classic Caesar!', 8.5, 2),
    ('Brewers House Salad', 9.5, 2),
    ('Steak Salad', 11.5, 2),
    ('Buffalo Chicken Salad', 11.5, 2),
    ('Soup of the Moment', 4.5, 2),
    ('Soup & Salad', 9.75, 2),
    ('Beef & Black Bean Chili', 4, 2),
    ('Basil Cream Ravioli', 14.5, 2),
    ('Fish Tacos', 12.5, 2),
    ('Chicken Fettuccine Alfredo', 10.5, 2),
    ('Beer Battered Fish & Chips', 14.5, 2),
    ('Sable Fish Ceviche', 12, 3),
    ('Empanadas', 8.5, 3),
    ('Pisco Clams', 10, 3),
    ('Quinoa Bruschetta', 8, 3),
    ('Stuffed Piquillo Peppers', 8.5, 3),
    ('Calamari Frito', 9.5, 3),
    ('Sweet Corn Humitas', 9.5, 3),
    ('Coco Shrimp', 11, 3),
    ('Avocado Wraps', 9.5, 3),
    ('Lettuce Wraps', 9.5, 3),
    ('Aguadito De Pollo', 3.5, 3),
    ('Sangria', 5.5, 3),
    ('Winter Spinach', 6, 3),
    ('Gorgonzola Wedge', 5.5, 3),
    ('Serrano Caesar', 5.5, 3),
    ('Cobb', 15.5, 3),
    ('Garlic Mushroom Lamb Linguine', 19.5, 3),
    ('Spinach Basil Fettucine With Milanesa', 18.5, 3),
    ('Tallarin (Peruvian Pan-Fried Noodles)', 16.5, 3),
    ('Tallarin (Organic Free-Range Chicken)', 16.5, 3),
    ('Shrimp Scampi Fettucine', 18.5, 3),
    ('Gorgonzola Fettucine', 18.5, 3),
    ('Shrimp With Angel Hair', 18.5, 3),
    ('Chicken With Angel Hair', 16.5, 3),
    ('Asado Borracho', 19.5, 3),
    ('Ribeye', 24.5, 3),
    ('Gorgonzola New York Strip', 24.5, 3),
    ('Pork Chop', 19.5, 3),
    ('Chancaca BBQ Pork Ribs', 16.5, 3),
    ('Grilled Lamb Chops', 26.5, 3),
    ('Sable Fish A Lo Macho', 23.5, 3),
    ('Macadamia Coconut Sable Fish', 23.5, 3),
    ('Sable Fish Sudado', 22.5, 3),
    ('Lomo Saltado', 19.5, 3),
    ('Emerald Saltado', 16.5, 3),
    ('Picante', 16.5, 3),
    ('Steak Milanesa', 17.5, 3),
    ('Peruvian Paella', 19.5, 3),
    ('Seco De Cordero Norteno (Braised Lamb Shank)', 19.5, 3),
    ('Aji De Gallina (Peruvian Curry)', 17.5, 3),
    ('Long Grain Risotto', 18.5, 3),
    ('Parihuela', 19.5, 3),
    ('Chaufa', 14.5, 3),
    ('Peru Burger', 13.5, 3),
    ('Sangria Burger', 13.5, 3);